version: '3.3'
services:
  portainer:
    image: portainer/portainer
    networks:
      - web
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.backend=portainer'
      - 'traefik.port=9000'
      - 'traefik.frontend.rule=Host:portainer.local'

  mysql:
    image: mysql:5
    command: --max_allowed_packet=32505856
    networks:
      - web
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./db_data:/var/lib/mysql
    labels:
      - 'traefik.backend=mysql'
      - 'traefik.port=3306'
      - 'traefik.frontend.rule=Host:mysql.local'

  pma:
    image: phpmyadmin/phpmyadmin
    networks:
      - web
    environment:
      PMA_HOSTS: mysql,172.16.8.40
      PMA_VERBOSES: localhost,dreeam
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    labels:
      - 'traefik.backend=pma'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:phpmyadmin.local'

  traefik:
    image: traefik
    networks:
      - web
    command: --web --api --docker --logLevel=INFO
    ports:
      - "80:80"     # The HTTP port
    labels:
      - 'traefik.backend=traefik'
      - 'traefik.port=8080'
      - 'traefik.frontend.rule=Host:traefik.local'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  web:
    image: nginx:latest
    networks:
      - web
    volumes:
      - ../app:/srv
      - ./site.conf:/etc/nginx/conf.d/00-site.conf
    labels:
      - 'traefik.port=80'
      - 'traefik.backend=amazee'
      - 'traefik.frontend.rule=Host:amazee.local'
    links:
      - php

  php:
    build:
      context: ./php
      args:
        XDEBUG_HOST: "172.17.0.1"
    networks:
      - web
    volumes:
      - ../app:/srv

networks:
  web:
    external:
      name: projects_web
